#!/bin/bash
set -e

echo "Installing glide..."

which glide > /dev/null 2>&1 || {
  mkdir -p ./glide
  curl -L https://github.com/Masterminds/glide/releases/download/0.12.1/glide-0.12.1-linux-amd64.tar.gz | tar xz -C ./glide --strip-components=1
  chmod 755 -R ./glide
  sudo mv ./glide/glide /usr/local/bin/
}

which glide > /dev/null 2>&1

echo "Installing dependencies with glide..."

glide up
glide install
